export default Object.freeze({
    Headers: 'HR Dashboard',
    cardDetails: [{ label: "Need to be Recruited", count: 18, color: "#3bc37d" }, { label: "Number of Resume in Pending", count: 50, color: "#f8b823" }, { label: "Resume in Process", count: 32, color: "#3ca3e4" },
    { label: "Pending Offer", count: 12, color: "#3ca3e4" }],
    cardDetails2019: [{ label: "Need to be Recruited", count: 54, color: "#3bc37d" }, { label: "Number of Resume Processed", count: 150, color: "#f8b823" }, { label: "Offer Accepted", count: 60, color: "#3ca3e4" },
    { label: "Employee Joined", count: 52, color: "#3ca3e4" }],
    cardDetails2020: [{ label: "Need to be Recruited", count: 65, color: "#3bc37d" }, { label: "Number of Resume Processed", count: 300, color: "#f8b823" }, { label: "Offer Accepted", count: 70, color: "#3ca3e4" },
    { label: "Employee Joined", count: 62, color: "#3ca3e4" }],
    cardDetails2021: [{ label: "Need to be Recruited", count: 74, color: "#3bc37d" }, { label: "Number of Resume Processed", count: 350, color: "#f8b823" }, { label: "Offer Accepted", count: 85, color: "#3ca3e4" },
    { label: "Employee Joined", count: 62, color: "#3ca3e4" }],
    cardDetails2022: [{ label: "Need to be Recruited", count: 79, color: "#3bc37d" }, { label: "Number of Resume Processed", count: 450, color: "#f8b823" }, { label: "Offer Accepted", count: 85, color: "#3ca3e4" },
    { label: "Employee Joined", count: 63, color: "#3ca3e4" }],
    chartType: ["Line", "PieChart", "Bar", "ScatterChart"],
    initialValue: [[
        ["Roles", "Vacant", "Resume Selected"],
        ['Senior Developer', 5, 4],
        ['Junior Developer', 4, 10],
        ['Full stack Developer', 3, 15],
        ['Intern', 4, 10]
    ], [
        ["Roles", "Processed Resume Position"],
        ["Senior Developer", 5],
        ["Junior Developer", 2],
        ["Full Stack Developer", 2],
        ["Inter", 2],
    ],
    [
        ["Role", "Resume Received", "Offer provided", "Employee Joined"],
        ["Senior Developer", 500, 200, 180],
        ["Junior Developer", 720, 100, 90],
        ["Full Stack Developer", 940, 170, 110],
        ["Inter", 1100, 120, 40],
    ],
    [
        ["Year", "Offer Accepted", "Employee Joined Company"],
        ["2019", 200, 180],
        ["2020", 120, 90],
        ["2021", 140, 110],
        ["2022", 60, 40],
    ]
    ],
    LineOptions: {
        title: "vacant resume variation",
        curveType: "function",
        legend: { position: "bottom" },
    },
    PieChartOptions: {
        title: "Resume Processed",
        pieHole: 0.4,
        is3D: false,
    },
    BarOptions: {
        chart: {
            title: "Selection Variation",

        },
    },
    ScatterChartOptions: {
        title: "Offer Acceptance and joined Variation",
        curveType: "function",
        legend: { position: "bottom" },
    },
    filterByYear: [2019, 2020, 2021, 2022],
    filterByRole: ['Senior Developer', 'Junior Developer', 'Full stack Developer', 'Intern'],
    Line: [
        ["Roles", "Vacant", "Resume Selected"],
        ['Senior Developer', 5, 4],
        ['Junior Developer', 4, 10],
        ['Full stack Developer', 3, 15],
        ['Intern', 4, 10]
    ],
    Line2019: [
        ["Roles", "Vacant", "Resume Selected"],
        ['Senior Developer', 3, 10],
        ['Junior Developer', 6, 15],
        ['Full stack Developer', 5, 25],
        ['Intern', 4, 2]
    ],
    Line2020: [
        ["Roles", "Vacant", "Resume Selected"],
        ['Senior Developer', 13, 10],
        ['Junior Developer', 4, 5],
        ['Full stack Developer', 2, 3],
        ['Intern', 2, 5]
    ],
    Line2021: [
        ["Roles", "Vacant", "Resume Selected"],
        ['Senior Developer', 3, 7],
        ['Junior Developer', 5, 9],
        ['Full stack Developer', 5, 8],
        ['Intern', 4, 9]
    ],
    Line2022: [
        ["Roles", "Vacant", "Resume Selected"],
        ['Senior Developer', 8, 12],
        ['Junior Developer', 4, 5],
        ['Full stack Developer', 4, 9],
        ['Intern', 2, 5]
    ],
    PieChart: [
        ["Roles", "Processed Resume Position"],
        ["Senior Developer", 5],
        ["Junior Developer", 2],
        ["Full Stack Developer", 2],
        ["Inter", 2],
    ],
    PieChart2019: [
        ["Roles", "Processed Resume Position"],
        ["Senior Developer", 8],
        ["Junior Developer", 9],
        ["Full Stack Developer", 3],
        ["Inter", 5],
    ],
    PieChart2020: [
        ["Roles", "Processed Resume Position"],
        ["Senior Developer", 7],
        ["Junior Developer", 5],
        ["Full Stack Developer", 3],
        ["Inter", 3],
    ],
    PieChart2021: [
        ["Roles", "Processed Resume Position"],
        ["Senior Developer", 6],
        ["Junior Developer", 4],
        ["Full Stack Developer", 7],
        ["Inter", 3],
    ],
    PieChart2022: [
        ["Roles", "Processed Resume Position"],
        ["Senior Developer", 3],
        ["Junior Developer", 9],
        ["Full Stack Developer", 4],
        ["Inter", 7],
    ],
    Bar: [
        ["Role", "Resume Received", "Offer provided", "Employee Joined"],
        ["Senior Developer", 500, 200, 180],
        ["Junior Developer", 720, 100, 90],
        ["Full Stack Developer", 940, 170, 110],
        ["Inter", 1100, 120, 40],
    ],
    Bar2019: [
        ["Role", "Resume Received", "Offer provided", "Employee Joined"],
        ["Senior Developer", 300, 400, 380],
        ["Junior Developer", 620, 100, 90],
        ["Full Stack Developer", 900, 570, 610],
        ["Inter", 1100, 830, 200],
    ],
    Bar2020: [
        ["Role", "Resume Received", "Offer provided", "Employee Joined"],
        ["Senior Developer", 490, 400, 380],
        ["Junior Developer", 620, 500, 490],
        ["Full Stack Developer", 970, 470, 210],
        ["Inter", 1100, 420, 200],
    ],
    Bar2021: [
        ["Role", "Resume Received", "Offer provided", "Employee Joined"],
        ["Senior Developer", 890, 800, 680],
        ["Junior Developer", 420, 300, 290],
        ["Full Stack Developer", 980, 473, 210],
        ["Inter", 1100, 320, 250],
    ],
    Bar2022: [
        ["Role", "Resume Received", "Offer provided", "Employee Joined"],
        ["Senior Developer", 990, 457, 347],
        ["Junior Developer", 424, 234, 124],
        ["Full Stack Developer", 980, 473, 245],
        ["Inter", 1234, 320, 250],
    ],
    ScatterChart: [
        ["Year", "Offer Accepted", "Employee Joined Company"],
        ["2019", 200, 180],
        ["2020", 120, 90],
        ["2021", 140, 110],
        ["2022", 60, 40],
    ],
    ScatterChart2019: [
        ["Year", "Offer Accepted", "Employee Joined Company"],
        ["January-March", 250, 180],
        ["April-July", 123, 90],
        ["August-October", 120, 110],
        ["November-December", 80, 40],
    ],
    ScatterChart2020: [
        ["Year", "Offer Accepted", "Employee Joined Company"],
        ["January-March", 300, 280],
        ["April-July", 220, 190],
        ["August-October", 440, 110],
        ["November-December", 20, 10],
    ],
    ScatterChart2021: [
        ["Year", "Offer Accepted", "Employee Joined Company"],
        ["January-March", 320, 280],
        ["April-July", 240, 130],
        ["August-October", 400, 120],
        ["November-December", 30, 10],
    ],
    ScatterChart2022: [
        ["Year", "Offer Accepted", "Employee Joined Company"],
        ["January-March", 420, 290],
        ["April-July", 340, 130],
        ["August-October", 450, 140],
        ["November-December", 40, 20],
    ],
});
